
backend:
  name: github
  repo: cance1a/cat_ribeiro-moreira
  branch: master
  client_id: Ov23liFuBzHGVfeQwHtv
  base_url: https://deluxe-treacle-5da07a.netlify.app

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "aluminio"
    label: "Alumínio"
    folder: "assets/img/aluminio"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { name: "title", label: "Título", widget: "string", required: false }
      - { name: "image", label: "Imagem", widget: "image", allow_external_url: true }
      - { name: "description_pt", label: "Descrição (PT)", widget: "text" }
      - { name: "description_en", label: "Descrição (EN)", widget: "text" }
      - { name: "description_es", label: "Descrição (ES)", widget: "text" }
      - { name: "description_fr", label: "Descrição (FR)", widget: "text" }

  - name: "construcoes"
    label: "Construções"
    folder: "assets/img/construcoes"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { name: "title", label: "Título", widget: "string", required: false }
      - { name: "image", label: "Imagem", widget: "image", allow_external_url: true }
      - { name: "description_pt", label: "Descrição (PT)", widget: "text" }
      - { name: "description_en", label: "Descrição (EN)", widget: "text" }
      - { name: "description_es", label: "Descrição (ES)", widget: "text" }
      - { name: "description_fr", label: "Descrição (FR)", widget: "text" }

  - name: "servicos"
    label: "Serviços"
    folder: "assets/img/servicos"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { name: "title", label: "Título", widget: "string", required: false }
      - { name: "image", label: "Imagem", widget: "image", allow_external_url: true }
      - { name: "description_pt", label: "Descrição (PT)", widget: "text" }
      - { name: "description_en", label: "Descrição (EN)", widget: "text" }
      - { name: "description_es", label: "Descrição (ES)", widget: "text" }
      - { name: "description_fr", label: "Descrição (FR)", widget: "text" }
